version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/expressProject
hooks:
  BeforeInstall:
    - location: scripts/before_install
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/after_install
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/application_stop
      timeout: 300
      runas: root

